### PR TITLE
Added MAD clipper to your_h5plotter.py

### PR DESCRIPTION
**Pull request by jkania7**
Added the optional ability to clip high/low values in your_h5plotter.py's frequency-time image.
This reduces the dynamic range that needs to be displayed making it easier to see faint pulses. 
Pixels are clipped based on a Median Absolute Deviation (MAD) filter.

### CODE REVIEW

**Comment by devanshkv** [comment]
This looks really good but needs a few changes.

- [ ] Refactor `smad` to `utils/math.py`.
- [ ] `mad_filter` argument should be of `bool` type.
- [ ] It should have a default value of `False` in the function argument. This would also require you to move to to the end of the argument list and would look like:


        def plot_h5(h5_file, save=True, detrend_ft=True, publication=False, mad_filter = False):

We realize that `detrend_ft` and `publication` is not an input to the `plot_h5` function in `your_h5plotter.py`. Can you please add that as well?

**Comment by KshitijAggarwal** [comment]
Also, try using `np.clip` in `smad`. That should be faster than the for loop.

**Comment by jkania7** [comment]
1) Refactor: done

2) mad_filter argument isn't necessary a bool,
             if the flag is not given-> mad_filter = false
             if the flag is given with no following arg -> mad_filter=3.0
             if the flag is given with a following arg -> mad_filter=that
arg
I'm not sure that this is the most correct solution, but it saves your from
having multiple flags.

3) I can rearrange the arguments, but that will require writing another
function to remap them to the way they are now. At least that's the only
way that I know how to do it, see the last comment @
https://stackoverflow.com/a/25553970
What does the advantage does the =False in the function call have above the
default=False already in the arg parser?

4) I can implement these two

Kshitij, this is surprisingly faster (1.6ms vs 1.66ms, see
bowser:/home/jwkania/notebooks/h5_mad.ipynb)
I would have gone with the np.clip anywhy, for the simplicity. However, it
might be useful to control how the values are mapped.
Maybe it is better to make the filtered values 0 instead of the clip value?
Or more pertinent to greenburst, the low values are wraps of the fpga
overflows, so does it make sense to make these values to +clip instead of
-clip? Etc.

**Comment by devanshkv** [comment]
In my experiment `np.clip` is much faster checkout in this [colab](https://colab.research.google.com/drive/1HffeGHnHcQr6YqyQ35kyYAGru2JsqNdT) notebook.

Also, please add a default value to `sigma` in `smad_cpu(freq_time, sigma,..)` and a default value of `0` in the function argument for `plot_h5`.

`plot_h5` is a standalone function and using mad_filter should be optional making the usage like:


        def plot_h5(h5_file, save=True, detrend_ft=True, publication=False, mad_filter = 0):

**Pull request merged**
